const accounts = [
    { id: 2, parent: null , sequence: '2' , account: 'Passivo', type: 'sintetica'},
    { id: 3, parent: 1, sequence: '1' , account: 'Circulante', type: 'sintetica'},
    { id: 18, parent: 14, sequence: '3' , account: 'Receita 03', type: 'analitica'},
    { id: 19, parent: 14, sequence: '4' , account: 'Receita 04', type: 'analitica'},
    { id: 1, parent: null, sequence: '1' , account: 'Ativo', type: 'sintetica'},
    { id: 23, parent: 14, sequence: '8' , account: 'Receita 08', type: 'analitica'},
    { id: 5, parent: 3, sequence: '2' , account: 'Banco', type: 'sintetica'},
    { id: 8, parent: 2, sequence: '2' , account: 'Fornenedores', type: 'sintetica'},
    { id: 16, parent: 14, sequence: '1' , account: 'Receita 01', type: 'analitica'},
    { id: 6, parent: 2, sequence: '1' , account: 'Impostos', type: 'sintetica'},
    { id: 25, parent: 15, sequence: '1' , account: 'Despesa 01', type: 'analitica'},
    { id: 9, parent: 7, sequence: '1', account: 'Móveis', type: 'analitica'},
    { id: 30, parent: 15, sequence: '12' , account: 'Despesa 12', type: 'analitica'},
    { id: 10, parent: 7, sequence: '2', account: 'Imóveis', type: 'analitica'},
    { id: 7, parent: 1, sequence: '2' , account: 'Imobilizado', type: 'sintetica'},
    { id: 14, parent: 13, sequence: '1' , account: 'Receitas', type: 'sintetica'},
    { id: 28, parent: 15, sequence: '4' , account: 'Despesa 04', type: 'analitica'},
    { id: 17, parent: 14, sequence: '2' , account: 'Receita 02', type: 'analitica'},
    { id: 27, parent: 15, sequence: '3' , account: 'Despesa 03', type: 'analitica'},
    { id: 13, parent: null, sequence: '3' , account: 'Resultado', type: 'sintetica'},
    { id: 20, parent: 14, sequence: '5' , account: 'Receita 05', type: 'analitica'},
    { id: 11, parent: 2, sequence: '3' , account: 'Patrimonio Liquido', type: 'sintetica'},
    { id: 24, parent: 14, sequence: '9' , account: 'Receita 40', type: 'analitica'},
    { id: 12, parent: 11, sequence: '1' , account: 'Lucro Acumulado', type: 'analitica'},
    { id: 4, parent: 3, sequence: '1' , account: 'Caixa', type: 'analitica'},
    { id: 22, parent: 14, sequence: '7' , account: 'Receita 07', type: 'analitica'},
    { id: 26, parent: 15, sequence: '2' , account: 'Despesa 02', type: 'analitica'},
    { id: 15, parent: 13, sequence: '2' , account: 'Despesas', type: 'sintetica'},
    { id: 21, parent: 14, sequence: '6' , account: 'Receita 06', type: 'analitica'},
    { id: 29, parent: 15, sequence: '5' , account: 'Despesa 05', type: 'analitica'},
    { id: 31, parent: 5, sequence: '1' , account: 'Banrisul', type: 'analitica'},
    { id: 32, parent: 5, sequence: '2' , account: 'Itau', type: 'analitica'}
];

module.exports = { accounts }